---
   - name: Create ssl directory
     become: yes
     file:
        path: /etc/nginx/ssl
        state: directory

   - name: Generate a new self signed SSL certificate file with OpenSSL
     become: yes
     command: chdir=/etc/nginx/ssl {{ item }}
     with_items:
       - openssl req -new -x509 -days 365 -nodes -out /etc/nginx/ssl/mattermostnginx.crt -keyout /etc/nginx/ssl/mattermostnginx.key -subj "/C=US/ST=North Carolina/L=Raleigh/O=NCSU/CN=mattermostnginx.example.com"

   - name: Change key file permissions
     become: yes
     file:
        path: /etc/nginx/ssl/mattermostnginx.key
        owner: root 
        group: root
        mode: '0400'

   - name: apply nginx ssl config template to /etc/nginx/sites-available/mattermost
     become: yes
     template: src=templates/root/nginx.ssl.j2 dest=/etc/nginx/sites-available/mattermost owner=root group=root mode=0664

   - name: Create a symlink
     become: yes
     file:
        src: /etc/nginx/sites-available/mattermost
        dest: /etc/nginx/sites-enabled/mattermost
        owner: root
        group: root
        state: link

   - name: Edit config.json to set up SiteURL
     become: yes
     lineinfile:
        path: /opt/mattermost/config/config.json
        regexp: '"SiteURL":'
        line: '        "SiteURL": "https://192.168.33.80",'
        backrefs: yes
        state: present

   - name: Restart mattermost service
     become: yes
     service:
        name: mattermost
        state: restarted

   - name: Start nginx service
     become: yes
     service:
        name: nginx
        state: restarted
