---
   - name: Install nginx and git 
     become: yes
     apt:
        name: nginx
        state: present
        update_cache: yes
        cache_valid_time: 3600
 
   - name: apply nginx config template to /etc/nginx/sites-available/mattermost
     become: yes
     template: src=templates/root/nginx.service.j2 dest=/etc/nginx/sites-available/mattermost owner=root group=root mode=0664 

   - name: remove nginx default site
     become: yes
     file:
        path: /etc/nginx/sites-enabled/default
        state: absent

   - name: Create a symlink
     become: yes
     file: 
        src: /etc/nginx/sites-available/mattermost
        dest: /etc/nginx/sites-enabled/mattermost
        owner: root
        group: root
        state: link

   - name: Edit config.json to set up listenaddress
     become: yes
     lineinfile:
        path: /opt/mattermost/config/config.json
        regexp: '"ListenAddress": ":8065",'
        line: '        "ListenAddress": "localhost:8065",'
        backrefs: yes
        state: present

   - name: Edit config.json to set up SiteURL
     become: yes
     lineinfile:
        path: /opt/mattermost/config/config.json
        regexp: '"SiteURL":'
        line: '        "SiteURL": "http://192.168.33.80:80",'
        backrefs: yes
        state: present

   - name: Restart mattermost service
     become: yes
     service:
        name: mattermost
        state: restarted

   - name: Start nginx service
     become: yes
     service:
        name: nginx
        state: restarted
